# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommendations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recommendations.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15recommendations.proto\"#\n\x15RecommendationRequest\x12\n\n\x02ID\x18\x01 \x01(\x03\"\xc3\x05\n\x12\x42ookRecommendation\x12\x11\n\tCLIENTNUM\x18\x01 \x01(\x03\x12\x16\n\x0e\x41ttrition_Flag\x18\x02 \x01(\t\x12\x14\n\x0c\x43ustomer_Age\x18\x03 \x01(\x03\x12\x0e\n\x06Gender\x18\x04 \x01(\t\x12\x17\n\x0f\x44\x65pendent_count\x18\x05 \x01(\x03\x12\x17\n\x0f\x45\x64ucation_Level\x18\x06 \x01(\t\x12\x16\n\x0eMarital_Status\x18\x07 \x01(\t\x12\x17\n\x0fIncome_Category\x18\x08 \x01(\t\x12\x15\n\rCard_Category\x18\t \x01(\t\x12\x16\n\x0eMonths_on_book\x18\n \x01(\x03\x12!\n\x19Total_Relantionship_Count\x18\x0b \x01(\x03\x12\x1e\n\x16Months_Inactive_12_mon\x18\x0c \x01(\x03\x12\x1d\n\x15\x43ontacts_Count_12_mon\x18\r \x01(\x03\x12\x14\n\x0c\x43redit_Limit\x18\x0e \x01(\x03\x12\x1b\n\x13Total_Revolving_Bal\x18\x0f \x01(\x03\x12\x17\n\x0f\x41vg_Open_To_Buy\x18\x10 \x01(\x03\x12\x1c\n\x14Total_Amt_Chng_Q4_Q1\x18\x11 \x01(\x02\x12\x17\n\x0fTotal_Trans_Amt\x18\x12 \x01(\x03\x12\x16\n\x0eTotal_Trans_Ct\x18\x13 \x01(\x03\x12\x1b\n\x13Total_Ct_Chng_Q4_Q1\x18\x14 \x01(\x02\x12\x1d\n\x15\x41vg_Utilization_Ratio\x18\x15 \x01(\x02\x12H\n@Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Cou\x18\x16 \x01(\x02\x12G\n?Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Co\x18\x17 \x01(\x02\"F\n\x16RecommendationResponse\x12,\n\x0frecommendations\x18\x01 \x01(\x0b\x32\x13.BookRecommendation2O\n\x0fRecommendations\x12<\n\tRecommend\x12\x16.RecommendationRequest\x1a\x17.RecommendationResponseb\x06proto3'
)




_RECOMMENDATIONREQUEST = _descriptor.Descriptor(
  name='RecommendationRequest',
  full_name='RecommendationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='RecommendationRequest.ID', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=60,
)


_BOOKRECOMMENDATION = _descriptor.Descriptor(
  name='BookRecommendation',
  full_name='BookRecommendation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='CLIENTNUM', full_name='BookRecommendation.CLIENTNUM', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Attrition_Flag', full_name='BookRecommendation.Attrition_Flag', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Customer_Age', full_name='BookRecommendation.Customer_Age', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Gender', full_name='BookRecommendation.Gender', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Dependent_count', full_name='BookRecommendation.Dependent_count', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Education_Level', full_name='BookRecommendation.Education_Level', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Marital_Status', full_name='BookRecommendation.Marital_Status', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Income_Category', full_name='BookRecommendation.Income_Category', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Card_Category', full_name='BookRecommendation.Card_Category', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Months_on_book', full_name='BookRecommendation.Months_on_book', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Total_Relantionship_Count', full_name='BookRecommendation.Total_Relantionship_Count', index=10,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Months_Inactive_12_mon', full_name='BookRecommendation.Months_Inactive_12_mon', index=11,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Contacts_Count_12_mon', full_name='BookRecommendation.Contacts_Count_12_mon', index=12,
      number=13, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Credit_Limit', full_name='BookRecommendation.Credit_Limit', index=13,
      number=14, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Total_Revolving_Bal', full_name='BookRecommendation.Total_Revolving_Bal', index=14,
      number=15, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Avg_Open_To_Buy', full_name='BookRecommendation.Avg_Open_To_Buy', index=15,
      number=16, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Total_Amt_Chng_Q4_Q1', full_name='BookRecommendation.Total_Amt_Chng_Q4_Q1', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Total_Trans_Amt', full_name='BookRecommendation.Total_Trans_Amt', index=17,
      number=18, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Total_Trans_Ct', full_name='BookRecommendation.Total_Trans_Ct', index=18,
      number=19, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Total_Ct_Chng_Q4_Q1', full_name='BookRecommendation.Total_Ct_Chng_Q4_Q1', index=19,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Avg_Utilization_Ratio', full_name='BookRecommendation.Avg_Utilization_Ratio', index=20,
      number=21, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Cou', full_name='BookRecommendation.Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Cou', index=21,
      number=22, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Co', full_name='BookRecommendation.Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Co', index=22,
      number=23, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=770,
)


_RECOMMENDATIONRESPONSE = _descriptor.Descriptor(
  name='RecommendationResponse',
  full_name='RecommendationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recommendations', full_name='RecommendationResponse.recommendations', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=772,
  serialized_end=842,
)

_RECOMMENDATIONRESPONSE.fields_by_name['recommendations'].message_type = _BOOKRECOMMENDATION
DESCRIPTOR.message_types_by_name['RecommendationRequest'] = _RECOMMENDATIONREQUEST
DESCRIPTOR.message_types_by_name['BookRecommendation'] = _BOOKRECOMMENDATION
DESCRIPTOR.message_types_by_name['RecommendationResponse'] = _RECOMMENDATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecommendationRequest = _reflection.GeneratedProtocolMessageType('RecommendationRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDATIONREQUEST,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:RecommendationRequest)
  })
_sym_db.RegisterMessage(RecommendationRequest)

BookRecommendation = _reflection.GeneratedProtocolMessageType('BookRecommendation', (_message.Message,), {
  'DESCRIPTOR' : _BOOKRECOMMENDATION,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:BookRecommendation)
  })
_sym_db.RegisterMessage(BookRecommendation)

RecommendationResponse = _reflection.GeneratedProtocolMessageType('RecommendationResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDATIONRESPONSE,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:RecommendationResponse)
  })
_sym_db.RegisterMessage(RecommendationResponse)



_RECOMMENDATIONS = _descriptor.ServiceDescriptor(
  name='Recommendations',
  full_name='Recommendations',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=844,
  serialized_end=923,
  methods=[
  _descriptor.MethodDescriptor(
    name='Recommend',
    full_name='Recommendations.Recommend',
    index=0,
    containing_service=None,
    input_type=_RECOMMENDATIONREQUEST,
    output_type=_RECOMMENDATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOMMENDATIONS)

DESCRIPTOR.services_by_name['Recommendations'] = _RECOMMENDATIONS

# @@protoc_insertion_point(module_scope)
